services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=ROOTPassword
      - MYSQL_DATABASE= voitures
      - MYSQL_USER=irinaslv
      - MYSQL_PASSWORD=irinaslv
    ports:
      - 3306:3306
  
  monapaache:
    image: irinaslv/monapache
    ports: 
      - 81:81
  
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 80:80

  monubuntu:
    image: irinaslv/monubuntu

