services:
  mariadb:
    image: mariadb
    environement:
      _MARIADB_USER
      _
      _
    ports:
      _3306:3306
  
  monapaache:
    image: irinaslv/monapache
    ports: 
      _80:80
  
  phpmyadmin:
    image: phpmyadmin
    environment:
      _PMA_HOST
    ports:
      _80:80

  monubuntu:
  image: irinaslv/monubuntu

  docker compose up:
